feat: More robust multi-threaded speed testing with more generalized provider support
XeroxDev/Loupedeck-plugin-Speedtest pull request #1
Opened 2022-03-25 16:13 UTC by mitchcapper

New Fast.com provider is not exposed to the user currently, but once options are added it can be.  This does a better job of evaluating high speed connections and follows more closely to official testers behavior.

I have imported some of my own code here, so if it looks like overkill that is likely why.  This gets me very reliable results over  many tests.   It should also scale the test to the size of the connection, like the actual tests.

No longer directly sub-classing HttpClient as I didn't see the benefit of going that route.

2022-03-25 16:21 UTC, XeroxDev requested changes
Expect the one thing, seems extremely good! Nice work!

2022-03-25 16:21 UTC, XeroxDev commented on SpeedtestPlugin/Classes/ByteBitSize.cs
> +namespace _IgnoreIgnoreIgnore
I'm not a bug friend of such namespaces. Is there any reason for this? If no, could you please change this?

2022-03-26 13:45 UTC, XeroxDev approved these changes

2022-03-26 13:46 UTC, XeroxDev commented
I'll merge it, when I'm doing a release.

2022-03-31 13:42 UTC, XeroxDev requested changes
I've tested your changes and I've to inform you, that those changes are breaking the plugins functionality.

1. you're using "min_ping" to display the ping. For me it's always 0.
2. Upload throws exceptions. See https://p.tswi.me/bojojepoxa.exception for full stack trace.
3. Download is still inaccurate. Plugin displays for me 42.8 MB/s but if I use the service you've implemented (fast.com / from netflix) I get 970Mb/s a.k.a ~120MB/s

2022-03-31 23:48 UTC, mitchcapper commented
Try again if still an issue please send the log:)

2022-04-02 09:39 UTC, XeroxDev approved these changes

2022-04-02 09:39 UTC, merged